const KEY='falcon_traders_v1';let data=JSON.parse(localStorage.getItem(KEY)||'[]'),editing=null;
const $=s=>document.querySelector(s), rows=$('#rows'), overlay=$('#overlay'), form=$('#form');
function money(v){return 'Rs '+Number(v||0).toLocaleString()}
function render(){const q=$('#search').value.toLowerCase();const list=data.filter(x=>(x.company+' '+x.vehicle).toLowerCase().includes(q));rows.innerHTML=list.map(x=>`<tr data-id="${x.id}"><td>${x.date}</td><td><b>${x.company}</b></td><td>${x.vehicle}</td><td>${x.received} T</td><td>${x.purchaseWeight} T</td><td>${money(x.purchaseRate)}</td><td>${money(x.saleRate)}</td><td><b>${money(x.netProfit)}</b></td><td><span class="status ${x.payment.toLowerCase()}">${x.payment}</span></td></tr>`).join('');
$('#empty').classList.toggle('hidden',data.length>0);$('#loads').textContent=data.length;$('#pending').textContent=data.filter(x=>x.payment==='Pending').length;$('#profit').textContent=money(data.reduce((a,x)=>a+Number(x.netProfit||0),0));localStorage.setItem(KEY,JSON.stringify(data));}
function openEntry(x){editing=x?.id||null;$('#formTitle').textContent=x?'Edit Entry':'New Entry';form.reset();form.elements.date.value=x?.date||new Date().toISOString().slice(0,10);form.elements.payment.value=x?.payment||'Pending';if(x){['company','vehicle','received','purchaseWeight','purchaseRate','saleRate','netProfit'].forEach(k=>form.elements[k].value=x[k]);}$('#deleteBtn').classList.toggle('hidden',!x);overlay.classList.remove('hidden')}
$('#add').onclick=()=>openEntry();$('#close').onclick=()=>overlay.classList.add('hidden');$('#search').oninput=render;
rows.onclick=e=>{const tr=e.target.closest('tr');if(tr)openEntry(data.find(x=>x.id===tr.dataset.id))};
form.onsubmit=e=>{e.preventDefault();const f=new FormData(form),x={id:editing||crypto.randomUUID(),date:f.get('date'),company:f.get('company').trim(),vehicle:f.get('vehicle').trim(),received:f.get('received'),purchaseWeight:f.get('purchaseWeight'),purchaseRate:f.get('purchaseRate'),saleRate:f.get('saleRate'),netProfit:f.get('netProfit'),payment:f.get('payment')};if(editing)data=data.map(a=>a.id===editing?x:a);else data.unshift(x);overlay.classList.add('hidden');render()};
$('#deleteBtn').onclick=()=>{if(editing&&confirm('Delete this entry?')){data=data.filter(x=>x.id!==editing);overlay.classList.add('hidden');render()}};render();