const KEY='falcon_traders_cycles_v2';let legacyState;try{legacyState=JSON.parse(localStorage.getItem(KEY)||'null')}catch{legacyState=null}let state={nextCount:3,cycles:[]},serverVersion=0,serverReady=false,saveQueue=Promise.resolve(),editing=null,editMode=false;const $=s=>document.querySelector(s),form=$('#form'),overlay=$('#overlay');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const money=v=>'Rs '+Number(v||0).toLocaleString();
const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
function dateParts(v){const s=String(v||'');let m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);if(m)return {y:+m[1],m:+m[2],d:+m[3]};m=s.match(/^(\d{2})\/(\d{2})\/(\d{4})$/);if(m)return {y:+m[3],m:+m[2],d:+m[1]};m=s.match(/^(\d{1,2})\s+([A-Za-z]{3})\s+(\d{2}|\d{4})$/);if(!m)return null;const month=months.findIndex(x=>x.toLowerCase()===m[2].toLowerCase())+1;return month?{y:m[3].length===2?2000+Number(m[3]):Number(m[3]),m:month,d:Number(m[1])}:null}
function todayIso(){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Karachi',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const get=t=>parts.find(p=>p.type===t).value;return `${get('year')}-${get('month')}-${get('day')}`}
function formatDate(v){const p=dateParts(v);return p&&p.m>=1&&p.m<=12&&p.d>=1&&p.d<=31?`${String(p.d).padStart(2,'0')} ${months[p.m-1]} ${String(p.y).slice(-2)}`:(v||'—')}
function toIsoDate(v){const p=dateParts(v);if(!p||!p.m||new Date(Date.UTC(p.y,p.m-1,p.d)).toISOString().slice(0,10)!==`${p.y}-${String(p.m).padStart(2,'0')}-${String(p.d).padStart(2,'0')}`)return '';return `${p.y}-${String(p.m).padStart(2,'0')}-${String(p.d).padStart(2,'0')}`}
function monthKey(v){const p=dateParts(v);return p&&p.m>=1&&p.m<=12?`${p.y}-${String(p.m).padStart(2,'0')}`:''}
function monthLabel(k){const [y,m]=k.split('-').map(Number);return `${months[m-1]} ${y}`}
let selectedMonth=monthKey(todayIso());
function shiftMonth(c){return monthKey(c.created)||monthKey(c.rows.find(r=>r.date)?.date)}
function monthCycles(){return state.cycles.filter(c=>shiftMonth(c)===selectedMonth)}
function moveMonth(n){const [y,m]=selectedMonth.split('-').map(Number),d=new Date(Date.UTC(y,m-1+n,1));selectedMonth=d.toISOString().slice(0,7);render()}
function cycleComplete(c){return c.rows.length>0&&c.rows.every(r=>r.vehicle&&r.status==='Delivered'&&r.payment==='Received')}
function renderMonthlySummary(preferred){const select=$('#summaryMonth'),keys=[...new Set(state.cycles.flatMap(c=>c.rows.map(r=>monthKey(r.date)||monthKey(c.created))))].filter(Boolean).sort().reverse(),current=preferred||select.value;select.innerHTML=keys.map(k=>`<option value="${k}">${monthLabel(k)}</option>`).join('');if(keys.includes(current))select.value=current;const key=select.value;const cycles=state.cycles.map((c,i)=>({c,i})).filter(({c})=>c.rows.some(r=>(monthKey(r.date)||monthKey(c.created))===key));const rows=cycles.flatMap(({c,i})=>c.rows.filter(r=>(monthKey(r.date)||monthKey(c.created))===key&&(r.vehicle)).map(r=>({r,i})));$('#summaryRows').innerHTML=rows.map(({r,i})=>`<tr><td>${esc(formatDate(r.date))}</td><td>${esc(r.vehicle)}</td><td>${esc(r.received||'—')}</td><td>${esc(r.purchaseRate||'—')}</td><td>${esc(r.saleRate||'—')}</td><td>${hasProfit(r)?esc(money(profitAmount(r))):"—"}</td></tr>`).join('')||'<tr><td colspan="6">No vehicle entries for this month.</td></tr>';const complete=cycles.filter(({c})=>cycleComplete(c));$('#summaryCycles').innerHTML=complete.map(({c,i})=>`<li>Shift ${i+1} — ${c.rows.length} vehicles — ${esc(formatDate(c.created))}</li>`).join('')||'<li>No completed shifts yet.</li>';const pending=cycles.reduce((n,{c})=>n+c.rows.filter(r=>(r.vehicle)&&r.payment!=='Received').length,0);const closed=cycles.length>0&&cycles.every(({c})=>cycleComplete(c))&&pending===0;$('#summaryStatus').textContent=key?(closed?'Closed — all shifts completed and payments received':`Open — ${cycles.length-complete.length} incomplete shift(s), ${pending} payment(s) remaining`):'No shifts yet';$('#summaryStatus').classList.toggle('closed',closed);$('#summaryTotal').textContent=money(rows.reduce((n,{r})=>n+profitAmount(r),0))}

function downloadMonthlySummary(){const key=$('#summaryMonth').value;if(!key)return;const cycles=state.cycles.map((c,i)=>({c,i})).filter(({c})=>c.rows.some(r=>(monthKey(r.date)||monthKey(c.created))===key));const rows=cycles.flatMap(({c})=>c.rows.filter(r=>(monthKey(r.date)||monthKey(c.created))===key&&(r.vehicle)));const safe=v=>{let s=String(v??'');if(/^[=+@]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'};const lines=[['Falcon Traders Monthly Summary',monthLabel(key)],['Status',$('#summaryStatus').textContent],[],['Date','Vehicle Number','Weight (tons)','Purchase Rate','Sale Rate','Net Profit']];rows.forEach(r=>lines.push([formatDate(r.date),r.vehicle,r.received,r.purchaseRate,r.saleRate,hasProfit(r)?profitAmount(r):'']));lines.push([],['Completed shifts']);cycles.filter(({c})=>cycleComplete(c)).forEach(({c,i})=>lines.push([`Shift ${i+1}`,`${c.rows.length} vehicles`,formatDate(c.created)]));lines.push([],['Monthly Total',rows.reduce((n,r)=>n+profitAmount(r),0)]);const blob=new Blob(['\uFEFF'+lines.map(row=>row.map(safe).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`Falcon-Traders-${key}.csv`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function request(url,options){const response=await fetch(url,{credentials:'same-origin',...options});let data;try{data=await response.json()}catch{data={}}if(!response.ok)throw Object.assign(new Error(data.error||'Server unavailable'),{status:response.status});return data}
async function loadShared(){const result=await request('/api/state');state=result.state;serverVersion=result.version;serverReady=true;render()}
function persistState(){const snapshot=JSON.parse(JSON.stringify(state));const work=saveQueue.then(async()=>{const result=await request('/api/state',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:serverVersion,state:snapshot})});serverVersion=result.version});saveQueue=work.catch(()=>{});return work}
async function saveChanges(){try{await persistState();return true}catch(err){alert(err.message);if(err.status===409)await loadShared();return false}}
async function bootstrap(){try{const [session,result]=await Promise.all([request('/api/session'),request('/api/state')]);editMode=session.editor;state=result.state;serverVersion=result.version;serverReady=true;render()}catch(err){$('#loadNotice').textContent='Could not load shared records. Check your connection and refresh the page.';$('#loadNotice').classList.remove('hidden')}}
function updateLegacyNotice(){const hasLegacy=legacyState?.cycles?.length&&state.cycles.length===0;$('#legacyNotice').classList.toggle('hidden',!hasLegacy);$('#importLegacy').classList.toggle('hidden',!editMode)}

function applyMode(){document.body.classList.toggle('view-mode',!editMode);$('#modeBtn').textContent=editMode?'Editor Mode':'View Mode';if(serverReady)updateLegacyNotice()}
function pendingPaymentEntries(){return monthCycles().flatMap(c=>c.rows).filter(r=>(r.vehicle)&&r.payment==='Pending')}
function hasAmount(v){return v!==''&&v!==null&&v!==undefined&&Number.isFinite(Number(v))}
function purchasedAmount(r){return Number(r.paymentAmount||0)}
function soldAmount(r){return Number(r.totalSoldAmount||0)}
function hasProfit(r){return hasAmount(r.paymentAmount)&&hasAmount(r.totalSoldAmount)&&hasAmount(r.commissionPaid)}
function profitAmount(r){return hasProfit(r)?Math.round(soldAmount(r)-purchasedAmount(r)-Number(r.commissionPaid)):0}
function dueAmount(r){return soldAmount(r)}
function renderPendingBreakdown(){const rows=pendingPaymentEntries().sort((a,b)=>(toIsoDate(b.date)||'').localeCompare(toIsoDate(a.date)||''));$('#pendingRows').innerHTML=rows.map(r=>'<tr><td>'+esc(formatDate(r.date))+'</td><td>'+esc(r.vehicle||'—')+'</td><td>'+esc(money(dueAmount(r)))+'</td></tr>').join('')||'<tr><td colspan="3" class="profit-empty">No pending payments.</td></tr>';$('#pendingListTotal').textContent=money(rows.reduce((sum,r)=>sum+dueAmount(r),0))}
function receivedProfitEntries(){return monthCycles().flatMap(c=>c.rows).filter(r=>(r.vehicle)&&r.payment==='Received')}
function renderProfitBreakdown(){const rows=receivedProfitEntries().sort((a,b)=>(toIsoDate(b.date)||'').localeCompare(toIsoDate(a.date)||''));$('#profitRows').innerHTML=rows.map(r=>'<tr><td>'+esc(formatDate(r.date))+'</td><td>'+esc(r.vehicle||'—')+'</td><td>'+(hasProfit(r)?esc(money(profitAmount(r))):'—')+'</td></tr>').join('')||'<tr><td colspan="3" class="profit-empty">No received payments yet.</td></tr>';$('#profitListTotal').textContent=money(rows.reduce((sum,r)=>sum+profitAmount(r),0))}
function render(){state.nextCount=Math.max(1,Math.min(20,state.nextCount||3));$('#vehicleCount').textContent=state.nextCount;const visible=monthCycles();$('#cycleTotal').textContent=visible.length;const completed=selectedMonth<monthKey(todayIso());$('#selectedMonthLabel').textContent=monthLabel(selectedMonth);$('.month-nav').classList.toggle('completed',completed);$('#addCycle').hidden=selectedMonth!==monthKey(todayIso());$('#pending').textContent=money(pendingPaymentEntries().reduce((total,r)=>total+dueAmount(r),0));$('#profit').textContent=money(receivedProfitEntries().reduce((a,r)=>a+profitAmount(r),0));if(!$('#profitOverlay').classList.contains('hidden'))renderProfitBreakdown();if(!$('#pendingOverlay').classList.contains('hidden'))renderPendingBreakdown();$('#cycles').innerHTML=visible.map((c,ci)=>`<section class="cycle"><div class="cycle-head"><div><small>SHIFT ${ci+1}</small><h2>${c.rows.length} Vehicles</h2></div><div class="cycle-head-actions"><span>${esc(formatDate(c.created))}</span><button type="button" class="delete-cycle" data-delete-cycle="${c.id}">Delete Shift</button></div></div><div class="vehicle-table-head"><span>Date</span><span>Vehicle Number</span><span>Status</span><span>Payment</span></div><div class="vehicle-list">${c.rows.map((r,ri)=>`<button class="vehicle-row vehicle-grid ${r.vehicle?'filled':''}" data-cycle="${c.id}" data-row="${r.id}"><span class="vehicle-date ${r.date?'':'empty-cell'}">${esc(r.date?formatDate(r.date):'—')}</span><span class="vehicle-number">${r.vehicle?`<b>${esc(r.vehicle)}</b>`:(selectedMonth===monthKey(todayIso())?'<small class="add-prompt">Add</small>':'—')}</span><span class="delivery-status ${r.vehicle?(r.status||'En Route').toLowerCase().replace(/\s+/g,'-'):'empty-cell'}">${r.vehicle?esc(r.status||'En Route'):'—'}</span><span class="status ${r.vehicle?(r.payment||'Pending').toLowerCase():'empty-cell'}">${r.vehicle?esc(r.payment||'Pending'):'—'}</span></button>`).join('')}</div></section>`).join('');$('#addCycle').textContent=visible.length?'+ Add Another Shift':'+ Add First Shift';applyMode()}
function addCycle(){if(!editMode||!serverReady||selectedMonth!==monthKey(todayIso()))return;const n=state.nextCount;state.cycles.push({id:crypto.randomUUID(),created:new Date().toLocaleDateString('en-GB'),rows:Array.from({length:n},(_,i)=>({id:crypto.randomUUID(),date:i===0?todayIso():'',vehicle:'',received:'',purchaseWeight:'',purchaseRate:'',saleRate:'',vehicleRentRate:'',vehicleRentTotal:'',totalSoldAmount:'',commissionPaid:'',rentReceived:'No',rentReceivedAmount:'',netProfit:'',paymentAmount:'',additionalInformation:'',orderSlip:'',receiving:'',otherRecord:'',status:'En Route',payment:'Pending'}))});render();saveChanges()}
function calculateNetProfit(){const purchaseWeight=Number(form.elements.purchaseWeight.value||0),vehicleRentRate=Number(form.elements.vehicleRentRate.value||0),vehicleRentTotal=purchaseWeight*vehicleRentRate;form.elements.vehicleRentTotal.value=Number.isFinite(vehicleRentTotal)?String(Math.round(vehicleRentTotal)):'0';const purchased=form.elements.paymentAmount.value,sold=form.elements.totalSoldAmount.value,commission=form.elements.commissionPaid.value;form.elements.netProfit.value=hasAmount(purchased)&&hasAmount(sold)&&hasAmount(commission)?String(Math.round(Number(sold)-Number(purchased)-Number(commission))):''}
function calculateReceivedAmounts(){const received=form.elements.received.value;[['purchaseRate','paymentAmount'],['saleRate','totalSoldAmount']].forEach(([rateName,totalName])=>{const rate=form.elements[rateName].value;form.elements[totalName].value=hasAmount(received)&&hasAmount(rate)?String(Math.round(Number(received)*Number(rate))):''});calculateNetProfit()}
['received','purchaseRate','saleRate'].forEach(name=>form.elements[name].addEventListener('input',calculateReceivedAmounts));
['purchaseWeight','vehicleRentRate','paymentAmount','totalSoldAmount','commissionPaid'].forEach(name=>form.elements[name].addEventListener('input',calculateNetProfit));
async function compressImage(file,maxBytes=75*1024){if(!file)return'';const bitmap=await createImageBitmap(file);let scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height)),quality=.82;const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');let out='';for(let n=0;n<12;n++){canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);const blob=await new Promise(r=>canvas.toBlob(r,'image/jpeg',quality));if(blob&&blob.size<=maxBytes){out=await new Promise(r=>{const fr=new FileReader();fr.onload=()=>r(fr.result);fr.readAsDataURL(blob)});break}if(quality>.42)quality-=.10;else scale*=.82}bitmap.close();if(!out)throw new Error('Could not reduce this image below 75 KB.');return out}
function compressedSize(data){const match=String(data||'').match(/^data:[^,]*;base64,([A-Za-z0-9+/=]+)$/);if(!match)return '';const encoded=match[1],bytes=Math.floor(encoded.length*3/4)-(encoded.endsWith('==')?2:encoded.endsWith('=')?1:0);return bytes<1024?bytes+' B':(bytes/1024).toFixed(1).replace(/\.0$/,'')+' KB'}
function renderUploadPreviews(r){['orderSlip','receiving','otherRecord'].forEach(k=>{const box=document.querySelector('[data-preview="'+k+'"]'),size=compressedSize(r[k]);box.innerHTML=r[k]?'<button type="button" class="uploaded-slip-link" data-slip-key="'+k+'"><img src="'+r[k]+'" alt="'+k+' uploaded image"></button>'+(size?'<small class="file-size-note">'+size+'</small>':''):'<small class="no-upload-note">No file uploaded</small>'})}
document.querySelectorAll('.slip-picker input[type="file"]').forEach(input=>input.addEventListener('change',()=>{const key={orderSlipFile:'orderSlip',receivingFile:'receiving',otherRecordFile:'otherRecord'}[input.name],box=document.querySelector('[data-preview="'+key+'"]');if(!box||!input.files[0])return;box.querySelector('.no-upload-note')?.remove();box.querySelector('.pending-upload-note')?.remove();const note=document.createElement('small');note.className='pending-upload-note';note.textContent='Selected: '+input.files[0].name;box.append(note)}));

function viewSlipMarkup(r,shiftLabel){
  const filled=v=>v!==null&&v!==undefined&&String(v).trim()!=='';
  const row=(label,value)=>'<div class="view-slip-line"><dt>'+esc(label)+'</dt><dd>'+esc(value)+'</dd></div>';
  const amount=(label,value)=>hasAmount(value)?row(label,money(value)):'';
  const pair=(label,value)=>filled(value)?row(label,value):'';
  const notes=String(r.additionalInformation||'').trim();
  const hasRent=r.rentReceived==='Yes'||hasAmount(r.rentReceivedAmount);
  const hasNotes=!!notes||hasRent;
  const hasReceiving=filled(r.received)||Number(r.paymentAmount||0)!==0||Number(r.totalSoldAmount||0)!==0||hasAmount(r.commissionPaid)||r.payment==='Received';
  const slips=[['orderSlip','1. Order slip'],['receiving','2. Receiving'],['otherRecord','3. Any other record']].filter(([key])=>filled(r[key]));
  const attachments=slips.length?'<div class="view-slip-attachments"><h3>Slips Attached</h3>'+slips.map(([key,label])=>'<div class="view-slip-attachment"><span>'+label+'</span><button class="uploaded-slip-link" type="button" aria-label="Open '+label+'"><img src="'+esc(r[key])+'" alt="'+label+'"><span>View slip</span></button>'+(compressedSize(r[key])?'<small>'+esc(compressedSize(r[key]))+'</small>':'')+'</div>').join('')+'</div>':'';
  const booking='<section class="view-slip-card"><h3 class="view-slip-booking-title">Booking Details</h3><dl>'+pair('Coal Loaded',filled(r.purchaseWeight)?r.purchaseWeight+' tons':'')+amount('Purchase Rate / ton',r.purchaseRate)+amount('Sale Rate / ton',r.saleRate)+amount('Vehicle Rent / ton',r.vehicleRentRate)+(hasAmount(r.purchaseWeight)&&hasAmount(r.vehicleRentRate)?row('Total Vehicle Rent',money(Math.round(Number(r.purchaseWeight)*Number(r.vehicleRentRate)))):'')+'</dl></section>';
  const noteCard=hasNotes?'<section class="view-slip-card"><h3>Rent received &amp; additional information</h3>'+(notes?'<p class="view-slip-note">'+esc(notes)+'</p>':'')+'<dl>'+(hasRent?row('Rent received',r.rentReceived||'No')+amount('Amount Received',r.rentReceivedAmount):'')+'</dl></section>':'';
  const receiving=hasReceiving?'<section class="view-slip-card"><h3>Receiving</h3><dl>'+pair('Coal Received',filled(r.received)?r.received+' tons':'')+amount('Total Purchased Amount',r.paymentAmount)+amount('Total Sold Amount',r.totalSoldAmount)+amount('Commission to be paid',r.commissionPaid)+row('Payment Due',r.payment||'Pending')+'</dl>'+(hasProfit(r)?'<div class="view-slip-profit"><span>Net Profit</span><strong>'+esc(money(profitAmount(r)))+'</strong></div>':'')+attachments+'</section>':(attachments?'<section class="view-slip-card">'+attachments+'</section>':'');
  return '<article class="view-slip"><header class="view-slip-header"><h2>Falcon Traders</h2><p>Vehicle slip · '+esc(shiftLabel)+'</p><div class="view-slip-identity"><strong>'+esc(r.vehicle||'Vehicle Details')+'</strong><span>'+esc(formatDate(r.date))+'</span></div>'+(r.vehicle?'<div class="view-slip-status">'+esc(r.status||'En Route')+'</div>':'')+'</header>'+booking+noteCard+receiving+'</article>';
}
function renderViewSlip(r,shiftLabel){let slip=$('#viewSlip');if(!slip){slip=document.createElement('div');slip.id='viewSlip';form.before(slip)}slip.innerHTML=editMode?'':viewSlipMarkup(r,shiftLabel);slip.hidden=editMode}

function openRow(cid,rid){const c=state.cycles.find(x=>x.id===cid),r=c?.rows.find(x=>x.id===rid);if(!r||(!r.vehicle&&shiftMonth(c)!==monthKey(todayIso())))return;editing={cid,rid};form.reset();Object.keys(r).forEach(k=>{if(form.elements[k])form.elements[k].value=k==='date'?(r[k]?formatDate(r[k]):''):r[k]});$('#calendarDate').value=toIsoDate(r.date)||'';calculateNetProfit();renderUploadPreviews(r);$('#cycleLabel').textContent='Shift '+(monthCycles().indexOf(c)+1);renderViewSlip(r,$('#cycleLabel').textContent);$('#formTitle').textContent=editMode?(r.vehicle?'Edit '+r.vehicle:'Vehicle Entry'):(r.vehicle||'Vehicle Details');Array.from(form.elements).forEach(el=>{if(el.id!=='saveBtn'&&!el.classList.contains('uploaded-slip-link'))el.disabled=!editMode});$('#saveBtn').classList.toggle('hidden',!editMode);overlay.classList.toggle('view-details',!editMode);overlay.classList.remove('hidden')}
$('#calendarDate').addEventListener('change',e=>{form.elements.date.value=e.target.value?formatDate(e.target.value):''});
$('#calendarDate').addEventListener('click',e=>{if(editMode&&typeof e.target.showPicker==='function'){try{e.target.showPicker()}catch(_){/* Native date control handles the tap. */}}});
$('#modeBtn').onclick=async()=>{if(editMode){try{await request('/api/logout',{method:'POST'});editMode=false;applyMode()}catch(err){alert(err.message)}return}$('#modePassword').value='';$('#passwordError').textContent='';$('#passwordOverlay').classList.remove('hidden');setTimeout(()=>$('#modePassword').focus(),0)};
$('#cancelPassword').onclick=()=>$('#passwordOverlay').classList.add('hidden');
$('#unlockEdit').onclick=async()=>{try{await request('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('#modePassword').value})});editMode=true;$('#passwordOverlay').classList.add('hidden');applyMode()}catch(err){$('#passwordError').textContent=err.message}};
$('#modePassword').addEventListener('keydown',e=>{if(e.key==='Enter')$('#unlockEdit').click()});
$('#importLegacy').onclick=async()=>{if(!editMode||!serverReady||state.cycles.length||!legacyState?.cycles?.length)return;if(!confirm('Import records saved on this device into the shared account?'))return;state=legacyState;render();if(await saveChanges()){$('#legacyNotice').classList.add('hidden');legacyState=null}};
$('#editCount').onclick=()=>{$('#stepper').classList.toggle('hidden');$('#editCount').textContent=$('#stepper').classList.contains('hidden')?'Edit':'Done'};$('#minus').onclick=()=>{if(!editMode)return;state.nextCount=Math.max(1,state.nextCount-1);render();saveChanges()};$('#plus').onclick=()=>{if(!editMode)return;state.nextCount=Math.min(20,state.nextCount+1);render();saveChanges()};$('#previousMonth').onclick=()=>moveMonth(-1);$('#nextMonth').onclick=()=>moveMonth(1);$('#addCycle').onclick=addCycle;$('#close').onclick=()=>overlay.classList.add('hidden');$('#cycles').onclick=e=>{const del=e.target.closest('.delete-cycle');if(del){if(!editMode)return;const c=state.cycles.find(x=>x.id===del.dataset.deleteCycle);if(c&&confirm('Delete this shift and all of its vehicle entries?')){state.cycles=state.cycles.filter(x=>x.id!==c.id);render();saveChanges()}return}const b=e.target.closest('.vehicle-row');if(b)openRow(b.dataset.cycle,b.dataset.row)};
document.addEventListener('click',e=>{const b=e.target.closest('.uploaded-slip-link');if(b){e.preventDefault();const img=b.querySelector('img');if(img&&img.src){$('#fullSlipImage').src=img.src;$('#imageViewer').classList.remove('hidden')}}});document.addEventListener('DOMContentLoaded',()=>{$('#closeImageViewer').onclick=()=>{$('#imageViewer').classList.add('hidden');$('#fullSlipImage').src=''};$('#imageViewer').onclick=e=>{if(e.target.id==='imageViewer')$('#closeImageViewer').click()}});
form.onsubmit=async e=>{e.preventDefault();if(!editMode)return;const c=state.cycles.find(x=>x.id===editing.cid),i=c.rows.findIndex(x=>x.id===editing.rid),old=c.rows[i],f=new FormData(form),isoDate=toIsoDate(f.get('date'));if(!isoDate){alert('Enter a valid date such as 25 Sep 26.');return}if(!old.vehicle&&(shiftMonth(c)!==monthKey(todayIso())||monthKey(isoDate)!==shiftMonth(c))){alert('New orders must be dated in the current month.');return}let orderSlip=old.orderSlip||'',receiving=old.receiving||'',otherRecord=old.otherRecord||'';try{const of=form.elements.orderSlipFile.files[0],rf=form.elements.receivingFile.files[0],xf=form.elements.otherRecordFile.files[0];if(of)orderSlip=await compressImage(of);if(rf)receiving=await compressImage(rf);if(xf)otherRecord=await compressImage(xf)}catch(err){alert(err.message);return}c.rows[i]={id:editing.rid,date:isoDate,vehicle:f.get('vehicle').trim(),received:f.get('received'),purchaseWeight:f.get('purchaseWeight'),purchaseRate:f.get('purchaseRate'),saleRate:f.get('saleRate'),vehicleRentRate:f.get('vehicleRentRate')||'',vehicleRentTotal:f.get('vehicleRentTotal')||'0',totalSoldAmount:f.get('totalSoldAmount')||'',commissionPaid:f.get('commissionPaid')||'',rentReceived:f.get('rentReceived')||'No',rentReceivedAmount:f.get('rentReceivedAmount')||'',netProfit:f.get('netProfit'),paymentAmount:f.get('paymentAmount')||'',additionalInformation:f.get('additionalInformation').trim(),orderSlip,receiving,otherRecord,status:f.get('status'),payment:f.get('payment')};render();if(await saveChanges())overlay.classList.add('hidden')};$('#pendingCard').onclick=()=>{renderPendingBreakdown();$('#pendingOverlay').classList.remove('hidden');$('#pendingClose').focus()};$('#pendingCard').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('#pendingCard').click()}};$('#pendingClose').onclick=()=>{$('#pendingOverlay').classList.add('hidden');$('#pendingCard').focus()};$('#pendingOverlay').onclick=e=>{if(e.target.id==='pendingOverlay')$('#pendingClose').click()};$('#profitCard').onclick=()=>{renderProfitBreakdown();$('#profitOverlay').classList.remove('hidden');$('#profitClose').focus()};$('#profitCard').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('#profitCard').click()}};$('#profitClose').onclick=()=>{$('#profitOverlay').classList.add('hidden');$('#profitCard').focus()};$('#profitOverlay').onclick=e=>{if(e.target.id==='profitOverlay')$('#profitClose').click()};
$('#monthlySummaryBtn').onclick=()=>{$('#summaryOverlay').classList.remove('hidden');renderMonthlySummary()};$('#summaryClose').onclick=()=>$('#summaryOverlay').classList.add('hidden');$('#summaryMonth').onchange=()=>renderMonthlySummary($('#summaryMonth').value);$('#downloadSummary').onclick=downloadMonthlySummary;bootstrap();
setInterval(()=>{if(serverReady&&!editMode&&overlay.classList.contains('hidden'))loadShared().catch(()=>{})},15000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&serverReady&&!editMode&&overlay.classList.contains('hidden'))loadShared().catch(()=>{})});

let calendarMonth=monthKey(todayIso());setInterval(()=>{const now=monthKey(todayIso());if(now!==calendarMonth){calendarMonth=now;selectedMonth=now;render()}},60000);
